### ISSUE TITLE
1.3.2 fails to build: Coordinate.cpp:270:72: error: no matching function for call to 'round(__gmp_expr<__mpq_struct [1], __gmp_binary_expr<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, long int, __gmp_binary_multiplies> >)'

### ISSUE THREAD

**Issue by sebastic** [Oslandia/SFCGAL#145]
SFCGAL 1.3.2 fails to build with CGAL 4.11:
```
[  0%] Building CXX object src/CMakeFiles/SFCGAL.dir/Coordinate.cpp.o
cd /build/sfcgal-1.3.2/obj-x86_64-linux-gnu/src && /usr/bin/c++  -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DSFCGAL_BUILD_SHARED -DSFCGAL_EXPORTS -I/build/sfcgal-1.3.2/obj-x86_64-linux-gnu/include -isystem /usr/include/x86_64-linux-gnu  -g -O2 -fdebug-prefix-map=/build/sfcgal-1.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wno-long-long -pedantic -Wpointer-arith -Wcast-align -Wcast-qual -Wno-overloaded-virtual -Wformat=2 -Winit-self -Wmissing-include-dirs -Wwrite-strings -Wno-error=undef -O2 -g -DNDEBUG -fPIC   -o CMakeFiles/SFCGAL.dir/Coordinate.cpp.o -c /build/sfcgal-1.3.2/src/Coordinate.cpp
[  1%] Building CXX object src/CMakeFiles/SFCGAL.dir/Envelope.cpp.o
[  1%] Building CXX object src/CMakeFiles/SFCGAL.dir/Exception.cpp.o
cd /build/sfcgal-1.3.2/obj-x86_64-linux-gnu/src && /usr/bin/c++  -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DSFCGAL_BUILD_SHARED -DSFCGAL_EXPORTS -I/build/sfcgal-1.3.2/obj-x86_64-linux-gnu/include -isystem /usr/include/x86_64-linux-gnu  -g -O2 -fdebug-prefix-map=/build/sfcgal-1.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wno-long-long -pedantic -Wpointer-arith -Wcast-align -Wcast-qual -Wno-overloaded-virtual -Wformat=2 -Winit-self -Wmissing-include-dirs -Wwrite-strings -Wno-error=undef -O2 -g -DNDEBUG -fPIC   -o CMakeFiles/SFCGAL.dir/Envelope.cpp.o -c /build/sfcgal-1.3.2/src/Envelope.cpp
cd /build/sfcgal-1.3.2/obj-x86_64-linux-gnu/src && /usr/bin/c++  -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DSFCGAL_BUILD_SHARED -DSFCGAL_EXPORTS -I/build/sfcgal-1.3.2/obj-x86_64-linux-gnu/include -isystem /usr/include/x86_64-linux-gnu  -g -O2 -fdebug-prefix-map=/build/sfcgal-1.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wno-long-long -pedantic -Wpointer-arith -Wcast-align -Wcast-qual -Wno-overloaded-virtual -Wformat=2 -Winit-self -Wmissing-include-dirs -Wwrite-strings -Wno-error=undef -O2 -g -DNDEBUG -fPIC   -o CMakeFiles/SFCGAL.dir/Exception.cpp.o -c /build/sfcgal-1.3.2/src/Exception.cpp
[  2%] Building CXX object src/CMakeFiles/SFCGAL.dir/Geometry.cpp.o
cd /build/sfcgal-1.3.2/obj-x86_64-linux-gnu/src && /usr/bin/c++  -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DSFCGAL_BUILD_SHARED -DSFCGAL_EXPORTS -I/build/sfcgal-1.3.2/obj-x86_64-linux-gnu/include -isystem /usr/include/x86_64-linux-gnu  -g -O2 -fdebug-prefix-map=/build/sfcgal-1.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wno-long-long -pedantic -Wpointer-arith -Wcast-align -Wcast-qual -Wno-overloaded-virtual -Wformat=2 -Winit-self -Wmissing-include-dirs -Wwrite-strings -Wno-error=undef -O2 -g -DNDEBUG -fPIC   -o CMakeFiles/SFCGAL.dir/Geometry.cpp.o -c /build/sfcgal-1.3.2/src/Geometry.cpp
/build/sfcgal-1.3.2/src/Coordinate.cpp: In member function 'CGAL::Lazy_kernel_generic_base<CGAL::Simple_cartesian<__gmp_expr<__mpq_struct [1], __mpq_struct [1]> >, CGAL::Simple_cartesian<CGAL::Interval_nt<false> >, CGAL::Cartesian_converter<CGAL::Simple_cartesian<__gmp_expr<__mpq_struct [1], __mpq_struct [1]> >, CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >, CGAL::Epeck>::FT SFCGAL::RoundVisitor::_roundFT(const FT&) const':
/build/sfcgal-1.3.2/src/Coordinate.cpp:270:72: error: no matching function for call to 'round(__gmp_expr<__mpq_struct [1], __gmp_binary_expr<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, long int, __gmp_binary_multiplies> >)'
                                SFCGAL::round( v.exact() * _scaleFactor ),
                                                                        ^
```

This issue was also reported by Joachim Reichel in [Debian Bug #876521](https://bugs.debian.org/876521)

**Comment by lrineau** [comment]
That seems related to https://github.com/CGAL/cgal/pull/2306, but that PR is merged into CGAL-4.11.

**Comment by lrineau** [comment]
Actually, no: your bug is a compilation bug ("no matching function found for ..."), and https://github.com/CGAL/cgal/pull/2306 was a link error ("missing symbol")

**Comment by sebastic** [comment]
It's a shame there has been no progress on this issue, or any other development activity for this project.

**Comment by sloriot** [comment]
@Oslandia do you need some help from CGAL devs here?

**Comment by peppsac** [comment]
FWIW I just compiled cgal (64023d2b3334eb2fed2581e397e456ad160b7871) and then sfcgal (46557e001ea35a8666e9551fdda550d5b9159618) with no problem (using g++ 7.2.0-7).

@sebastic what g++ version are you using?

**Comment by sebastic** [comment]
g++ 7.2.0-14 from Debian unstable.

You can reproduce the issue on Debian unstable with the cgal 4.11 packages from experimental.

**Comment by peppsac** [comment]
Indeed I could reproduce it with the exp package.
And to be able to reproduce it from git version of cgal, you need to enable the use of `GMPXX`.

With cgal built like this sfcgal compiles ok :
```
cmake .. -DCMAKE_INSTALL_PREFIX=/opt/cgal
```

To reproduce the build issue I need to use:
```
cmake .. -DCMAKE_INSTALL_PREFIX=/opt/cgal -DWITH_GMPXX=True
```

I don't really know cgal nor sfcgal so any help would be welcome indeed :)

**Comment by peppsac** [comment]
Seems like this diff fixes the build:
```diff
diff --git a/src/Coordinate.cpp b/src/Coordinate.cpp
index 773f5c4..014e9df 100644
--- a/src/Coordinate.cpp
+++ b/src/Coordinate.cpp
@@ -266,10 +266,17 @@ private:
 
 
     Kernel::FT _roundFT( const Kernel::FT& v ) const {
+        #ifdef CGAL_USE_GMPXX
+        return Kernel::FT( ::mpq_class(
+                               SFCGAL::round( v.exact() * _scaleFactor ),
+                               _scaleFactor
+                           ) ) ;
+        #else
         return Kernel::FT( CGAL::Gmpq(
                                SFCGAL::round( v.exact() * _scaleFactor ),
                                _scaleFactor
                            ) ) ;
+        #endif
     }
 
 };
diff --git a/src/numeric.h b/src/numeric.h
index 0b6f5ed..6c18818 100644
--- a/src/numeric.h
+++ b/src/numeric.h
@@ -57,6 +57,20 @@ inline double round( const double& v )
     }
 }
 
+#ifdef CGAL_USE_GMPXX
+/**
+ * @brief floor a rational to an integer
+ */
+SFCGAL_API ::mpz_class floor( const ::mpq_class& v ) ;
+/**
+ * @brief ceil a rational to an integer
+ */
+SFCGAL_API ::mpz_class ceil( const ::mpq_class& v ) ;
+/**
+ * @brief round a rational to an integer
+ */
+SFCGAL_API ::mpz_class round( const ::mpq_class& v ) ;
+#endif
 
 /**
  * @brief floor a rational to an integer
```

**Comment by mhugo** [comment]
@peppsac looks good to me. Could you add a pull request ?

If I understand correctly, this is has nothing to do with CGAL/SFCGAL versions. It is related to a compilation option (WITH_GPMXX) that has not been correctly tested ? It probably resolves a long standing bug.

**Comment by sebastic** [comment]
With the patch by @peppsac the build still fails with the following errors:
```
/build/sfcgal-1.3.2/src/detail/io/Serialization.cpp:42:28:   required from here
/usr/include/boost/serialization/access.hpp:116:11: error: 'class __gmp_expr<__mpq_struct [1], __mpq_struct [1]>' has no member named 'serialize'; did you mean 'canonicalize'?
         t.serialize(ar, file_version);
         ~~^~~~~~~~~
         canonicalize
```
```
/build/sfcgal-1.3.2/src/detail/io/Serialization.cpp:59:28:   required from here
/usr/include/boost/serialization/access.hpp:116:11: error: 'class __gmp_expr<__mpq_struct [1], __mpq_struct [1]>' has no member named 'serialize'; did you mean 'canonicalize'?
         t.serialize(ar, file_version);
         ~~^~~~~~~~~
         canonicalize
```
```
/build/sfcgal-1.3.2/src/detail/io/WktReader.cpp:650:32: error: '__gnu_cxx::__alloc_traits<std::allocator<__gmp_expr<__mpq_struct [1], __mpq_struct [1]> > >::value_type {aka class __gmp_expr<__mpq_struct [1], __mpq_struct [1]>}' has no member named 'to_double'
         p.setM( coordinates[3].to_double() );
                                ^~~~~~~~~
/build/sfcgal-1.3.2/src/detail/io/WktReader.cpp:659:32: error: '__gnu_cxx::__alloc_traits<std::allocator<__gmp_expr<__mpq_struct [1], __mpq_struct [1]> > >::value_type {aka class __gmp_expr<__mpq_struct [1], __mpq_struct [1]>}' has no member named 'to_double'
         p.setM( coordinates[2].to_double() );
                                ^~~~~~~~~
```

**Comment by peppsac** [comment]
Oops, my bad, I screwed up my compile test.
I'm going to open another PR that fixes the remaining issues.

**Comment by sebastic** [comment]
The transition to CGAL 4.11 started in Debian today. The updated cgal package will most likely also find its way into the upcoming Ubuntu LTS (bionic), so this issue will start to affect a much larger number of users.

**Comment by Talkless** [comment]
Any progress with this?

We have issue that we kinda have to upgrade to Postgis 2.4 due to latest PostgreSQL security fix (about schema qualifications), but Postgis 2.4 is no longer built with sfcgal support on Debian due to this compilation issue.

Postgis without sfcgal does not have sfcgal-specific `st_orientation()` which is used in our production system.

**Comment by sloriot** [comment]
Please check if #157 fixes the issue for you.
