### PR TITLE
fix postgis build, bump version to 1.3.4

### PR DESCRIPTION
**Pull request by vmora**
adds -lCGAL -lCGAL_Core to sfcgal-config --libs

@sloriot It does work with postgis now, but I'm a bit lost with the autolink stuff. Is it the right solution, or is there something better to do ?

@lbartoletti can you try out this patch ?

### CODE REVIEW

**Comment by vmora** [comment]
@sloriot I'm going to check... but it'd seem a tad weird to do that

... and check done, we don't

**Comment by sloriot** [comment]
OK so the file `sfcgal-config` is created while configuring SFCGAL with cmake. And I guess this script is used by postgis to add some extra config flags. There are a few things that worries me, maybe we should have a quick voice meeting at some point with @mhugo to sort things out.

**Comment by lbartoletti** [comment]
@vmora Build successful with postgis 23 cgal 4.10 and SFCGAL 1.3.4 on FreeBSD 11 amd64.
I launch the other configurations.

**Comment by sebastic** [comment]
PostGIS 2.4.4 still fails to build with SFCGAL 1.3.4 on Debian unstable:
```make
x86_64-linux-gnu-gcc -g -O2 -fdebug-prefix-map=/build/postgis-2.4.4+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security  -fPIC -DPIC  -Wall -Wmissing-prototypes -I../rt_core -I../../liblwgeom  -I/usr/include/gdal -I/usr/include   -c raster2pgsql.c
/bin/bash ../../libtool --mode=link x86_64-linux-gnu-gcc -g -O2 -fdebug-prefix-map=/build/postgis-2.4.4+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security  -fPIC -DPIC  -Wall -Wmissing-prototypes -I../rt_core -I../../liblwgeom  -I/usr/include/gdal -I/usr/include   ../rt_core/librtcore.a raster2pgsql.o -Wl,-z,relro -Wl,-z,now -L../../liblwgeom/.libs -llwgeom -L/usr/lib -lgdal  -L/usr/lib/x86_64-linux-gnu -lgeos_c  -lc -lm -o raster2pgsql
libtool: link: x86_64-linux-gnu-gcc -g -O2 -fdebug-prefix-map=/build/postgis-2.4.4+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPIC -Wall -Wmissing-prototypes -I../rt_core -I../../liblwgeom -I/usr/include/gdal -I/usr/include raster2pgsql.o -Wl,-z -Wl,relro -Wl,-z -Wl,now -o .libs/raster2pgsql  ../rt_core/librtcore.a -L../../liblwgeom/.libs /build/postgis-2.4.4+dfsg/liblwgeom/.libs/liblwgeom.so -L/usr/lib -lgdal -L/usr/lib/x86_64-linux-gnu -lgeos_c -lc -lm
//usr/lib/x86_64-linux-gnu/libSFCGAL.so.1: undefined reference to `operator>>(std::istream&, __mpz_struct*)'
//usr/lib/x86_64-linux-gnu/libSFCGAL.so.1: undefined reference to `operator<<(std::ostream&, __mpz_struct const*)'
collect2: error: ld returned 1 exit status
```

**Comment by vmora** [comment]
@sebastic we worked this out with @sloriot, is it possible for you to test #162 plz ?

**Comment by sebastic** [comment]
This is #162, and the build in question contain that change because its using SFCGAL 1.3.4.

**Comment by vmora** [comment]
@sebastic oups I meant #163 for SFCGAL 1.3.5.

**Comment by sebastic** [comment]
Confirmed fixed with the changes from #163, many thanks to @sloriot for fixing these issues.
