### ISSUE TITLE
1.3x branch has commits not present in master

### ISSUE THREAD

**Issue by tigerfoot** [Oslandia/SFCGAL#146]
See 
https://github.com/Oslandia/SFCGAL/compare/1.3.x

Especially 
src/algorithm/Intersection3D.cpp line 34 
CGAL/Polygon_mesh_processing/corefinement.h

This create a problem for packaging when some version still have to build with CGAL 4.7 and newer having CGAL 4.11 

Is it possible to have a code able to build nicely with CGAL 4.7 and > 4.10.1 ?

**Comment by robe2** [comment]
I'm having this issue building against master, I assume it's caused by this:

[ 27%] [32mBuilding CXX object src/CMakeFiles/SFCGAL.dir/algorithm/Intersection3D.cpp.obj[0m

> E:/jenkins/CGAL/sfcgal/branches/1.3/src/algorithm/Intersection3D.cpp:34:55: fatal error: CGAL/Polygon_mesh_processing/corefinement.h: No such file or directory
 #include <CGAL/Polygon_mesh_processing/corefinement.h>
                                                       ^
compilation terminated.
src/CMakeFiles/SFCGAL.dir/build.make:638: recipe for target 'src/CMakeFiles/SFCGAL.dir/algorithm/Intersection3D.cpp.obj' failed
make[2]: *** [src/CMakeFiles/SFCGAL.dir/algorithm/Intersection3D.cpp.obj] Error 1
CMakeFiles/Makefile2:118: recipe for target 'src/CMakeFiles/SFCGAL.dir/all' failed
make[1]: *** [src/CMakeFiles/SFCGAL.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lbartoletti** [comment]
Still true on 1.3.7 and master?

**Comment by tigerfoot** [comment]
Can't say actually. Now openSUSE is at least CGAL 4.12 but mostly 4.14 and
