### PR TITLE
Fix SFCGAL with CGAL 5

### LINKED ISSUE #198: CGAL 5.0 support
Your package fails to build with CGAL 5.0 Beta 2. I modified the top-level CMakeLists.txt as follows:
- add set(CMAKE_CXX_STANDARD 14)
- remove block with "c++98"
- remove "4.3" from find_package() call

When trying to link the unit test, it fails with
```/usr/bin/ld: CMakeFiles/unit-test-SFCGAL.dir/SFCGAL/algorithm/Force3DTest.cpp.o: in function `SFCGAL_algorithm_Force3DTest::testIgnoreEmpty::test_method()':
./obj-x86_64-linux-gnu/test/unit/./test/unit/SFCGAL/algorithm/Force3DTest.cpp:57: undefined reference to `SFCGAL::algorithm::force3D(SFCGAL::Geometry&, 
CGAL::Lazy_exact_nt<boost::multiprecision::number<boost::multiprecision::backends::gmp_rational, (boost::multiprecision::expression_template_option)1> > const&)'
/usr/bin/ld: CMakeFiles/unit-test-SFCGAL.dir/SFCGAL/algorithm/Force3DTest.cpp.o: in function `SFCGAL_algorithm_Force3DTest::testPointForceZ::test_method()':
./obj-x86_64-linux-gnu/test/unit/./test/unit/SFCGAL/algorithm/Force3DTest.cpp:65: undefined reference to `SFCGAL::algorithm::force3D(SFCGAL::Geometry&, CGAL::Lazy_exact_nt<boost::multiprecision::number<boost::multiprecision::backends::gmp_rational, (boost::multiprecision::expression_template_option)1> > const&)'
/usr/bin/ld: CMakeFiles/unit-test-SFCGAL.dir/SFCGAL/algorithm/Force3DTest.cpp.o: in function `SFCGAL_algorithm_Force3DTest::testPointForceZWithValue::test_method()':
./obj-x86_64-linux-gnu/test/unit/./test/unit/SFCGAL/algorithm/Force3DTest.cpp:71: undefined reference to `SFCGAL::algorithm::force3D(SFCGAL::Geometry&, CGAL::Lazy_exact_nt<boost::multiprecision::number<boost::multiprecision::backends::gmp_rational, (boost::multiprecision::expression_template_option)1> > const&)'
/usr/bin/ld: CMakeFiles/unit-test-SFCGAL.dir/SFCGAL/algorithm/Force3DTest.cpp.o: in function `SFCGAL_algorithm_Force3DTest::test_MixedLineString2D3D::test_method()':
./obj-x86_64-linux-gnu/test/unit/./test/unit/SFCGAL/algorithm/Force3DTest.cpp:82: undefined reference to `SFCGAL::algorithm::force3D(SFCGAL::Geometry&, CGAL::Lazy_exact_nt<boost::multiprecision::number<boost::multiprecision::backends::gmp_rational, (boost::multiprecision::expression_template_option)1> > const&)'
/usr/bin/ld: CMakeFiles/unit-test-SFCGAL.dir/SFCGAL/algorithm/UnionTest.cpp.o: in function `SFCGAL_algorithm_UnionTest::PolygonPolygon2::test_method()':
./obj-x86_64-linux-gnu/test/unit/./test/unit/SFCGAL/algorithm/UnionTest.cpp:230: undefined reference to `SFCGAL::algorithm::translate(SFCGAL::Geometry&, CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq>)'
/usr/bin/ld: ./obj-x86_64-linux-gnu/test/unit/./test/unit/SFCGAL/algorithm/UnionTest.cpp:234: undefined reference to `SFCGAL::algorithm::translate(SFCGAL::Geometry&, CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq>)'
/usr/bin/ld: CMakeFiles/unit-test-SFCGAL.dir/SFCGAL/algorithm/UnionTest.cpp.o: in function `SFCGAL_algorithm_UnionTest::PolygonPolygon3::test_method()':
./obj-x86_64-linux-gnu/test/unit/./test/unit/SFCGAL/algorithm/UnionTest.cpp:259: undefined reference to `SFCGAL::algorithm::translate(SFCGAL::Geometry&, CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq>)'
/usr/bin/ld: ./obj-x86_64-linux-gnu/test/unit/./test/unit/SFCGAL/algorithm/UnionTest.cpp:261: undefined reference to `SFCGAL::algorithm::translate(SFCGAL::Geometry&, CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq>)'
/usr/bin/ld: CMakeFiles/unit-test-SFCGAL.dir/SFCGAL/algorithm/UnionTest.cpp.o: in function `SFCGAL_algorithm_UnionTest::VolumeVolume::test_method()':
./obj-x86_64-linux-gnu/test/unit/./test/unit/SFCGAL/algorithm/UnionTest.cpp:363: undefined reference to `SFCGAL::algorithm::translate(SFCGAL::Geometry&, CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq>)'
/usr/bin/ld: CMakeFiles/unit-test-SFCGAL.dir/SFCGAL/algorithm/UnionTest.cpp.o:./obj-x86_64-linux-gnu/test/unit/./test/unit/SFCGAL/algorithm/UnionTest.cpp:370: more undefined references to `SFCGAL::algorithm::translate(SFCGAL::Geometry&, CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq>)' follow
/usr/bin/ld: CMakeFiles/unit-test-SFCGAL.dir/SFCGAL/transform/ForceZOrderPointsTest.cpp.o: in function `SFCGAL_transform_ForceZOrderPointsTest::simple::test_method()':
./obj-x86_64-linux-gnu/test/unit/./test/unit/SFCGAL/transform/ForceZOrderPointsTest.cpp:40: undefined reference to `SFCGAL::transform::ForceZOrderPoints::ForceZOrderPoints(CGAL::Lazy_exact_nt<boost::multiprecision::number<boost::multiprecision::backends::gmp_rational, (boost::multiprecision::expression_template_option)1> > const&)'
collect2: error: ld returned 1 exit status```

### PR DESCRIPTION
**Pull request by lbartoletti**
I added a condition to link sfcgal with gmpxx since it is necessary when cgal version >= 5.

I tested locally with postgis. As gmpxx is in sfcgal, there is no need to add gmpxx in sfcgal_config.in

Tests: 
- Ubuntu and CGAL 5.0 (CI Travis)
- FreeBSD, CGAL 4.13 (local and CI Cirrus)
- FreeBSD, CGAL 5.0.2 (local)

Fix #198

### CODE REVIEW

**Comment by lbartoletti** [comment]
@devrimgunduz  @sebastic @joachim-reichel Can you test it? Thanks

**Comment by sebastic** [comment]
The Debian package already has similar patches:

 * https://salsa.debian.org/debian-gis-team/sfcgal/-/blob/master/debian/patches/fix-linker-error.patch
 * https://salsa.debian.org/debian-gis-team/sfcgal/-/blob/master/debian/patches/fix-ftbfs-with-cgal-5.x.patch
 * https://salsa.debian.org/debian-gis-team/sfcgal/-/blob/master/debian/patches/sfcgal-config.patch

Those work for us with CGAL 5.

**Comment by joachim-reichel** [comment]
Configuring and building as done by the sfcgal Debian package works fine.
